model_parameters:
  total_yield_kt: 1400.0
  gamma_yield_fraction: 0.05
  Compton_KE: 1.28
  pulse_param_a: 0.01
  pulse_param_b: 0.37
  rtol: 0.0001
  numerical_integration_method: Radau
  magnetic_field_model: igrf
  time_max: 100.0
  num_time_points: 300
  date: 7/9/1962
geometry:
  burst_point:
    latitude_deg: 16.466667
    longitude_deg: -169.633333
    altitude_km: 400.0
  target_point:
    latitude_deg: 16.466667
    longitude_deg: -169.633333
    altitude_km: 0.0
